sequenceDiagram
    Browser->>+Server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    Server-->>-Browser: HTML DOC
    Browser->>+Server: Get https://studies.cs.helsinki.fi/exampleapp/main.css
    Server-->>-Browser: CSS File
    Browser->>+Server: https://studies.cs.helsinki.fi/exampleapp/main.js
    Server-->>-Browser: JS File
    Browser->>+Server: https://studies.cs.helsinki.fi/exampleapp/dsts.json
    Server-->>-Browser: Content / Date
    Browser->>+Server: POST https://studies.cs.helsinki.fi/exampleapp/new_note (User post new note)
    Server-->>-Browser: HTTP status code 302 Found (Requesting Browser to make another GET request)
    Browser->>+Server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    Server-->>-Browser: HTML DOC
    Browser->>+Server: Get https://studies.cs.helsinki.fi/exampleapp/main.css
    Server-->>-Browser: CSS File
    Browser->>+Server: https://studies.cs.helsinki.fi/exampleapp/main.js
    Server-->>-Browser: JS File
    Browser->>+Server: https://studies.cs.helsinki.fi/exampleapp/dsts.json
    Server-->>-Browser: Content / Date